name: Python Package using Pip and Venv

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # - name: Lint with flake8
    #   run: |
    #     source venv/bin/activate
    #     pip install flake8
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        source venv/bin/activate
        pip install pytest
        python -m pytest

    - name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v4.0.1
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
      slug: bobleesj/cif-cleaner